### ISSUE TITLE
Request to reconsider JC_HOME

### ISSUE THREAD

**Issue by minkyn** [fidesmo/gradle-javacard#25]
Using an environment variable is easy but not convenient in all cases. In my case, I would like to distribute the project along with JCDK to my team to save the hassle of local reconfiguration. However, it is the JC_HOME that stands in the way and teammates have to define this environment variable in their respective bashrc.

In addition, if I use IDE such as IntelliJ, it won't inherit the environment variable from my bashrc, so you cannot use the built-in gradle build button as it would complain about the missing JC_HOME.

How about making a gradle property variable to replace JC_HOME, or at least use that gradle property and fall back to JC_HOME if undefined? In that case, I can set the value in my build.gradle or even gradle.properties without the need for environment variable, and both the aforementioned cases would be solved.

**Comment by pepegar** [comment]
Hi @minkin. Yes, I like your proposal, we didn't think of an use case like that before. We are adding this to our backlog but cannot promise it will be done directly, so if you want to do it yourself, please go ahead and we would be extremely happy to accept your contribution. We can help you if you struggle with something in the process.

**Comment by minkin** [comment]
Hi!

If think you tagged my username by accident? I suppose you meant @minkyn?

Anyways, I wish you the best of luck with your project :)

/ Minkin

**Comment by pepegar** [comment]
Indeed, thanks @minkin. @minkyn https://github.com/fidesmo/gradle-javacard/issues/25#issuecomment-261204420

**Comment by minkyn** [comment]
https://github.com/fidesmo/gradle-javacard/pull/26

Please review the PR. Thanks!

**Comment by sergkh** [comment]
PR accepted and new version of a library released

**Comment by minkyn** [comment]
Has it been sync'ed to the maven repo at http://releases.marmeladburk.fidesmo.com?

**Comment by sergkh** [comment]
Yes
